# Generated by Django 5.0 on 2024-01-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileUploading', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
